# Generated by Django 4.1.6 on 2025-07-26 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="created_by",
        ),
        migrations.AlterUniqueTogether(
            name="recipeingredient",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="recipe",
        ),
        migrations.AlterUniqueTogether(
            name="userpantry",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userpantry",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="userpantry",
            name="user",
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.DeleteModel(
            name="RecipeIngredient",
        ),
        migrations.DeleteModel(
            name="UserPantry",
        ),
    ]
